# Generated by Django 5.0.6 on 2024-08-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_admin_customuser_is_bibliotecario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="dni",
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
